# Generated by Django 6.0.1 on 2026-01-12 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('store_provider_url', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'product_status',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatusPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField()),
                ('log', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_pipeline', to='products.products')),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_pipeline', to='products.productstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_product_pipeline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_status_pipeline',
                'ordering': ['-posted'],
            },
        ),
    ]
