# Generated by Django 6.0.1 on 2026-01-12 22:07

from django.db import migrations


def add_bulk_data(apps, schema_editor):
    ProductStatus = apps.get_model('products', 'ProductStatus')

    objetos = [
        ProductStatus(id=1, name='created', label='Created'),
        ProductStatus(id=2, name='deleted', label='Deleted'),
    ]

    # Usar bulk_create para eficiencia
    ProductStatus.objects.bulk_create(objetos)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_bulk_data)
    ]
