# Generated by Django 6.0.1 on 2026-01-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_status_initial_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
